### ISSUE TITLE
An error occurred while Layout/SpaceInsideHashLiteralBraces cop was inspecting ...

### ISSUE THREAD

**Issue by bekicot** [julianrubisch/pronto-standardrb#6]
After installing and do `pronto run`
I get:
```
An error occurred while Layout/SpaceInsideHashLiteralBraces cop was inspecting /path/to/file
```

doing
```
standardrb /path/to/file
```
and
```
rubocop /path/to/file
```
works as expected

**Comment by ragingdave** [comment]
I have a similar situation, and for me, the files where an error occurs often will change run to run somehow. This seems to be swallowing up errors though that would otherwise be surfaced.

Another example is:
```
An error occurred while Bundler/DuplicatedGem cop was inspecting /app/Gemfile.
```
Where we do in fact have a duplicated gem, but it doesn't indicate anything helpful and the error is hidden during CI runs and local runs.
